import React, { useEffect, useState } from 'react';
import { BACKEND_URL } from '../constants.ts';
import { CartCard } from '../components/CartCard.tsx';
import { Loader2 } from 'lucide-react';
import { html } from '../utils.ts';

const Home = () => {
  const [carts, setCarts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchCarts = async () => {
      try {
        const response = await fetch(`${BACKEND_URL}/api/carts`);
        if (response.ok) {
          const data = await response.json();
          setCarts(data);
        }
      } catch (error) {
        console.error("Error fetching carts:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchCarts();
  }, []);

  return html`
    <div className="container mx-auto px-4 py-8">
      <div className="mb-10 text-center">
        <h1 className="text-4xl md:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 mb-4">
          Discover AI Micro-Apps
        </h1>
        <p className="text-lg text-gray-400 max-w-2xl mx-auto">
          Explore single-file applications generated by Gemini. From games to utilities, see what's possible with a simple prompt.
        </p>
      </div>

      <div className="mb-6 flex items-center space-x-2">
        <h2 className="text-2xl font-bold text-white">Recent Carts</h2>
        <div className="h-px bg-gray-700 flex-grow ml-4"></div>
      </div>

      ${loading ? html`
        <div className="flex justify-center items-center py-20">
          <${Loader2} className="animate-spin text-blue-500" size=${48} />
        </div>
      ` : carts.length === 0 ? html`
        <div className="text-center py-16 bg-gray-800/50 rounded-2xl border border-gray-700 border-dashed">
          <p className="text-gray-400 text-lg">No carts created yet. Be the first!</p>
        </div>
      ` : html`
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          ${carts.map((cart) => html`<${CartCard} key=${cart.id} cart=${cart} />`)}
        </div>
      `}
    </div>
  `;
};

export default Home;
